name: Changelog

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - '.github/**'
      - '**/*.md'
      - 'LICENSE'
      - 'NOTICE'

permissions:
  contents: read
  pull-requests: write

jobs:
  check:
    name: Check Changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Check if CHANGELOG.md was updated
        id: changelog
        run: |
          if git diff --name-only origin/${{ github.base_ref }}..HEAD | grep -q "^CHANGELOG.md$"; then
            echo "updated=true" >> $GITHUB_OUTPUT
          else
            echo "updated=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Comment on PR
        if: steps.changelog.outputs.updated == 'false'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comment = `⚠️ **Changelog Update Required**
            
            This PR appears to contain functional changes but doesn't update the CHANGELOG.md file.
            Please add an entry to CHANGELOG.md describing your changes.
            
            If this PR contains only non-functional changes (like CI updates, documentation, etc.), you can ignore this message.`;
            
            // Check if we already commented
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            
            const botComment = comments.find(comment => 
              comment.user.type === 'Bot' && 
              comment.body.includes('Changelog Update Required')
            );
            
            if (!botComment) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: comment,
              });
            }